apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tarot-core.fullname" . }}-config
  labels:
    {{- include "tarot-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}
