{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tarot-core.fullname" . }}-migration
  labels:
    {{- include "tarot-core.migration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "tarot-core.migration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.migration.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          env:
            {{- $secretName := include "tarot-core.databaseSecretName" . }}
            {{- $usernameKey := include "tarot-core.databaseUsernameKey" . }}
            {{- $passwordKey := include "tarot-core.databasePasswordKey" . }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $usernameKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $passwordKey }}
            - name: DATABASE_URL
              value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@{{ .Values.database.host }}:{{ .Values.database.port | default 5432 }}/{{ .Values.database.dbName }}?schema=public&sslmode={{ .Values.database.sslMode | default "disable" }}"
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
{{- end }}
