name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master
      - develop
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  nest-ci:
    name: NestJS CI
    uses: mandacode-labs/workflows/.github/workflows/nest-ci.yml@main
    with:
      node-version: "25"
      enable-coverage: true
      coverage-threshold: 0
      enable-security-scan: true

  docker-test:
    name: Docker Test
    needs: nest-ci
    uses: mandacode-labs/workflows/.github/workflows/docker-test.yml@main
    with:
      images: |
        [
          {"dockerfile": "app.Dockerfile"},
          {"dockerfile": "mig.Dockerfile"}
        ]
      base-path: "docker"
      enable-hadolint: true
      enable-trivy: true
      trivy-severity: "HIGH,CRITICAL"

  helm-test:
    name: Helm Test
    needs: nest-ci
    uses: mandacode-labs/workflows/.github/workflows/helm-test.yml@main
    with:
      charts: |
        [
          {"dir": "deploy/chart"}
        ]
      helm-version: "v4.1.1"
      kubernetes-version: "v1.35.0"
      enable-kubeconform: true
      enable-install-test: false
